### ISSUE TITLE
Cannot install the demo ... Incompatible module

### ISSUE THREAD

**Issue by ahmedmusawir** [gladchinda/build-react-pagination-demo#1]
yarn install v1.10.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "10.10.0"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by gladchinda** [comment]
Hello @ahmedmusawir, can you check this out:
https://github.com/yarnpkg/yarn/issues/5727#issuecomment-386108534

**Comment by ahmedmusawir** [comment]
Thanx for your reply... I just down graded to 8.x and now all's well.
