### ISSUE TITLE
What language is this?

### ISSUE THREAD

**Issue by oleksii-lukin** [gladchinda/build-react-pagination-demo#3]
https://github.com/gladchinda/build-react-pagination-demo/blob/8bd177696e153ed3c6a073d2ea1aa0389a492b2f/src/components/Pagination.js#L118

`case (hasLeftSpill && !hasRightSpill): {`
this is definitely not JS, because you would have either false or true and you have 3 conditions inside and anyway it's highlighted as error

**Comment by oleksii-lukin** [comment]
![image](https://user-images.githubusercontent.com/1281970/56657233-30245a00-66a0-11e9-9140-c48053905e2e.png)

**Comment by gladchinda** [comment]
@llamerr The code snippet you highlighted is **valid JavaScript**. I don't seem to understand why your code editor or IDE is highlighting parts of the block as invalid code. Check to ensure that the linting and syntax highlighting capabilities of your code editor supports the ES6 syntax.
